### ISSUE TITLE
Implement multiple lap system

### ISSUE THREAD

**Issue by Panquesito7** [panqkart/panqkart#3]
To make races longer, we should implement a lap, bug-free system.
We should ensure that:

- A player can't just go back and win all laps in a few seconds by touching the node.
- The player must pass through all the map to be able to complete one lap.
  - I was thinking of placing a particular node on the map (say on the middle map) to be able to pass to another lap.

If you have any other ideas, let me know! Thanks. 🙂

**Comment by Pantyhose-X** [comment]
other ideas
add [Roller coaster](https://en.wikipedia.org/wiki/Roller_coaster) Railroad track Straight Line Liftoff
![1](https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/PKDHypersonicDrop.jpg/800px-PKDHypersonicDrop.jpg)
