### ISSUE TITLE
Contradiction at match start

### ISSUE THREAD

**Issue by LoneWolfHT** [panqkart/panqkart#64]
![image](https://user-images.githubusercontent.com/28972859/215571270-31ff68b3-b867-4566-acd7-f7e749fc64b0.png)
See the chat message and the HUD message next to the hotbar

**Comment by Panquesito7** [comment]
The HUD specifies the total of minimum required players.
I guess we should specify the number of missing players instead. 🙂

**Comment by LoneWolfHT** [comment]
Ah, you could maybe show `<current players> / <needed players>` there
