### ISSUE TITLE
Too many numbers at the end of lap times

### ISSUE THREAD

**Issue by LoneWolfHT** [panqkart/panqkart#65]
![image](https://user-images.githubusercontent.com/28972859/215571865-2191f9bf-52dd-4769-9c7a-179bb20c74c9.png)

This can be fixed with something like:
```lua
minetest.chat_send_player(player, string.format("Game's up! You finished the race in %.2f seconds.", time))
```
(Will show `69.66 seconds` in the chat, `2` decimal places)

**Comment by Panquesito7** [comment]
That's an awesome idea! Would you like to work on this?

**Comment by LoneWolfHT** [comment]
I could if you wanted me to, otherwise I will avoid adding anything new to my rather stuffed schedule :P

**Comment by Panquesito7** [comment]
> I could if you wanted me to, otherwise I will avoid adding anything new to my rather stuffed schedule :P

Feel free to choose and let me know. 🙂

**Comment by Panquesito7** [comment]
Well, I'll guess I'll work on this. Will still give you credit. Thanks. :)
